version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_optica
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: optics_store
    ports:
      - "3307:3306"
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
    driver: local
